lib/pton_web/router.ex
defmodule PtonWeb.Router do
  use PtonWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pton.Plugs.SetUser
  end

  scope "/auth", PtonWeb do
    pipe_through :browser

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

  scope "/", PtonWeb do
    pipe_through :browser # Use the default browser stack

    get "/", LinkController, :new
    if Mix.env == :dev do
      get "/kitchen-sink", PageController, :kitchen_sink
    end

    get "/links/mine", LinkController, :mine
    resources "/links", LinkController
    get "/:slug", LinkController, :follow
  end

  # Other scopes may use custom stacks.
  # scope "/api", PtonWeb do
  #   pipe_through :api
  # end
end

lib/pton_web/views/layout_view.ex
defmodule PtonWeb.LayoutView do
  use PtonWeb, :view
end

lib/pton_web/templates/layout/_alerts.html.eex
<%# https://medium.com/elixir-magic/writing-a-blog-engine-in-phoenix-and-elixir-part-11-better-ui-f17f3d7efa85 %>
<%= if flash = get_flash(@conn, :info) do %>
<div class="alert alert-info" role="alert">
  <%= flash %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<%= if flash = get_flash(@conn, :success) do %>
<div class="alert alert-success" role="alert">
  <%= flash %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<%= if flash = get_flash(@conn, :error) do %>
<div class="alert alert-error" role="alert">
  <%= flash %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

lib/pton_web/templates/layout/_navigation.html.eex
<nav class="navbar navbar-default navbar-fixed-top pton-main-navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#pton-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <img src="/images/logo.svg" alt="TigerLinks Logo">
      <%= unless @conn.assigns[:hide_site_name] do %>
        TigerLinks
      <% end %>
    </a>
  </div>

  <div class="collapse navbar-collapse" id="pton-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link "All Links", to: link_path(@conn, :index) %></li>
      <li class="dropdown">
        <%= if @conn.assigns[:user] do %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @conn.assigns.user.netid %><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link "My Links", to: link_path(@conn, :mine) %></li>
          <li><%= link "Sign out", to: auth_path(@conn, :delete) %></li>
        </ul>
        <% else %>
        <%= link "Sign in", to: auth_path(@conn, :request, "cas") %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

lib/pton_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Casey Chow">
  <meta name="theme-color" content="#ffffff">

  <title><%= @conn.assigns[:title] || "TigerLinks" %></title>

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ff9909">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>

<body>
  <%= render "_navigation.html", conn: @conn %>

  <div class="container">
    <div class="row alerts">
      <%= render "_alerts.html", conn: @conn %>
    </div>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

  </div> <!-- /container -->
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>